### ISSUE TITLE
PR_Relance-proposition-2

### ISSUE THREAD

**Issue by karinerob** [Eoxia/dolitemplate#12]
Mail pour les relances de propositions commerciales-2 @todo

**Comment by elisa34** [comment]
Sujet :
2ème relance de proposition

Contenu :

Bonjour,

Je reviens vers vous pour savoir si vous aviez pu prendre connaissance de mon précédent mail. Êtes-vous disponible pour un rapide appel téléphonique le __DAY_TEXT__  __DAY__? 
Où puis-je contacter quelqu’un de votre part pour avancer sur cette problématique? Merci de votre réponse.


Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL

**Comment by ocemag** [comment]
Sujet :
2ème relance de proposition

Contenu :

Bonjour,

Je reviens vers vous pour savoir si vous avez pris le temps de consulter notre proposition. Seriez-vous disponible pour un appel téléphonique le DAY_TEXT DAY?
Pourrais-je contacter quelqu’un de votre part pour faire avancer la situation ? Merci de votre réponse.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
