### ISSUE TITLE
CO_Facturation-commandes

### ISSUE THREAD

**Issue by lmag** [Eoxia/dolitemplate#16]

**Comment by elisa34** [comment]
Sujet :
Facturation de la commande :  __REF_CLIENT__

Contenu :

Bonjour,

Suite à [nom de la prestation] effectué(e) le __DATE_YMD__ et correspondant au n° [], nous vous adressons votre facture ci-joint : __DIRECTDOWNLOAD_URL_INVOICE__
Il est possible de régler ce montant par [chèque, virement ou espèces.] ou de payer en ligne ici : __ONLINE_PAYMENT_URL__

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by nicolas-eoxia** [comment]
il manque
- DIRECTDOWNLOAD_URL_INVOICE
- ONLINE_PAYMENT_URL

**Comment by ocemag** [comment]
Sujet :
Facturation de la commande : REF_CLIENT

Contenu :

Bonjour,

Suite à [nom de la prestation] effectué(e) le DATE_YMD correspondant au n° REF, nous vous transmettons votre facture ci-joint : DIRECTDOWNLOAD_URL_INVOICE
Il est possible de régler ce montant par [chèque, virement ou espèces.] ou de payer en ligne ici : ONLINE_PAYMENT_URL

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
