### ISSUE TITLE
PR_Cloture-proposition

### ISSUE THREAD

**Issue by eoxiaaudrey** [Eoxia/dolitemplate#20]

**Comment by elisa34** [comment]
Sujet :
Clôture proposition

Contenu :

Bonjour,

Je vous remercie de l’intérêt que vous portez à notre société, je regrette toutefois que nous ne puissions accepter votre proposition. Nous sommes actuellement sous contrat jusqu’au __DATE_YMD__ .  Cependant après l’expiration de ce contrat, nous serons heureux de discuter avec vous de la possibilité de faire des affaires à l’avenir.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL

**Comment by ocemag** [comment]
Sujet :
Clôture proposition

Contenu :

Bonjour,

Je vous remercie de l’intérêt que vous portez à notre société, je regrette toutefois que nous ne puissions accepter votre proposition. Nous sommes actuellement sous contrat jusqu’au DATE_YMD . Cependant après l’expiration de ce contrat, nous serons heureux de discuter avec vous de la possibilité de faire des affaires à l’avenir.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
