### ISSUE TITLE
CO_Envoi-commandes

### ISSUE THREAD

**Issue by lmag** [Eoxia/dolitemplate#25]

**Comment by elisa34** [comment]
Sujet :
Envoie de la commande

Contenu :

Bonjour,

A la date du __DATE_YMD__ , vous avez passé commande de [nom du produit, la quantité demandée, les références, couleurs…] et nous vous en remercions.
Votre commande a bien été prise en compte.
Elle sera acheminée par voie postale à l’adresse suivante :
[Nom Prénom - Adresse - Code postal Ville]
Votre colis devrait vous parvenir sous un délai de __AMOUNT__ jour.

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by ocemag** [comment]
Sujet :
Envoie de votre commande

Contenu :

Bonjour,

A la date du DATE_YMD , vous avez passé une commande de [nom du produit, la quantité demandée, les références…] et nous vous en remercions. Votre commande a bien été prise en compte.
Elle sera livrée à l'adresse suivante :
THIRDPARTY_NAME THIRDPARTY_ADRESS THIRDPARTY_ZIP THIRDPARTY_TOWN
Votre colis devrait vous parvenir sous un délai de AMOUNT jours.
Pour suivre votre commande cliquez ici: SHIPPINGTRACKNUMURL.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
