### ISSUE TITLE
CO_Accusé-reception-commandes

### ISSUE THREAD

**Issue by lmag** [Eoxia/dolitemplate#26]
Sujet : 
Accusé de réception de votre commande concernant le projet : __PROJECT_NAME__.

Contenu : 

Bonjour,

Nous vous remercions pour votre commande concernant le projet n° __PROJECT_REF__ - __PROJECT_NAME__.
Nous accusons réception de celle-ci, vous trouverez en retour notre confirmation de commande :  __REF__ avec votre numéro de commande.
Après lecture, si vous le souhaitez vous pouvez signer en ligne très simplement en cliquant sur le lien suivant :
__EXTRAFIELD_SIGNATURE_LINK__
Votre signature vaudra alors pour une acceptation ferme et définitive de la commande.

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by lmag** [comment]
Si MBI donc à ne pas mettre en natif
Après lecture, si vous le souhaitez vous pouvez signer en ligne très simplement en cliquant sur le lien suivant :
EXTRAFIELD_SIGNATURE_LINK
Votre signature vaudra alors pour une acceptation ferme et définitive de la commande.

**Comment by ocemag** [comment]
Sujet :
Accusé de réception de votre commande liée au projet : PROJECT_NAME.

Contenu :

Bonjour,

Nous vous remercions pour votre commande liée au projet n° PROJECT_REF - PROJECT_NAME.
Nous accusons réception de celle-ci. 
Vous trouverez en retour notre confirmation de commande : REF avec votre numéro de commande.
Après lecture, si vous le souhaitez vous pouvez signer en ligne en cliquant sur le lien suivant :
EXTRAFIELD_SIGNATURE_LINK
Votre signature vaudra pour acceptation ferme et définitive de la commande.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
