### ISSUE TITLE
PJ_Envoi-création-projet

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#32]
Sujet :
Récapitulation création du projet:

Contenu :

Bonjour,

Pour faire un point sur ce début de projet :
- réference client: __REF_CLIENT__
- nom du projet : __PROJECT_NAME__ 
- date de début :__DATE_YMD__
- date de fin : __DATE_YMD__

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by ocemag** [comment]
Sujet :
Récapitulation création du projet:

Contenu :

Bonjour,

Voici un récapitulatif des informations principales de ce lancement de projet :

réference client: REF_CLIENT
nom du projet : PROJECT_NAME
date de début :DATE_YMD
date de fin : DATE_YMD

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
