### ISSUE TITLE
PJ_Envoi-bilan-projet

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#33]
Sujet :
Bilan du projet: __PROJECT_NAME__.

Contenu :

Bonjour,

Demande du client: [écrire la demande]
-Date de début :__DATE_YMD__
-Date de fin : __DATE_YMD__
-Résultats atteints: 
-Ecarts: 
-Observations: 
-Conclusion:

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by ocemag** [comment]
Sujet :
Bilan du projet: PROJECT_NAME.

Contenu :

Bonjour,

Voici le bilan de votre projet : 
Demande initiale du client: [écrire la demande]
-Date de début : DATE_YMD
-Date de fin : DATE_YMD
-Résultats atteints :
-Ecarts :
-Observations :
-Conclusion :

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLAD
