### ISSUE TITLE
RQ_Envoi-demande-prix

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#34]
Sujet :
Demande de prix

Contenu :

Bonjour,

Par la présente, je me permets de vous contacter au nom de la société __MYCOMPANY_NAME__ .
Suite à la visite de votre site internet, la direction des achats souhaite obtenir des informations complémentaires concernant __REF__ .
Pouvez-vous nous communiquer les tarifs pour la/les références ci-dessus.
N'hésitez pas à me contacter si toutefois vous souhaitez des renseignements complémentaires concernant cette demande de tarifs.

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by ocemag** [comment]
Sujet :
Demande de prix

Contenu :

Bonjour,

Je me permets de vous contacter au nom de la société MYCOMPANY_NAME .
Après consultation de votre site internet, la direction des achats souhaite obtenir des informations complémentaires concernant REF .
Pouvez-vous nous communiquer les tarifs pour la/les références ci-dessus.
N'hésitez pas à me contacter si toutefois vous souhaitez des renseignements complémentaires concernant cette demande de tarifs.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
