### ISSUE TITLE
RQ_Relance-demande-prix

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#35]
Sujet :
Relance demande de prix

Contenu :

Bonjour,

Par la présente, je me permets de vous recontacter au nom de la société __MYCOMPANY_NAME__ .
Suite à la visite de votre site internet, la direction des achats souhaite obtenir des informations complémentaires concernant __REF__.
Pouvez-vous nous communiquer les tarifs pour la/les référence(s) ci-dessus.
N'hésitez pas à me contacter si toutefois vous souhaitez des renseignements complémentaires concernant cette demande de tarifs.

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by ocemag** [comment]
Sujet :
Relance demande de prix

Contenu :

Bonjour,

Je me permets de vous recontacter au nom de la société MYCOMPANY_NAME .
Après la consultation de votre site internet, la direction des achats souhaite obtenir des informations complémentaires concernant REF.
Pouvez-vous nous communiquer les tarifs pour la/les référence(s) ci-dessus.
N'hésitez pas à me contacter si toutefois vous souhaitez des renseignements complémentaires concernant cette demande de tarifs.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
