### ISSUE TITLE
RQ_Accepter-demande-prix

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#36]
Sujet :
Demande de prix acceptée

Contenu :

Bonjour,

Suite à l’analyse de votre demande, veuillez trouver ci-joint notre proposition de devis qui, si vous l’acceptez, par apposition de votre signature, vaudra bon de commande. Merci de nous le renvoyer signé par courriel ou par la poste.
Pour visualiser votre devis cliquez sur la pièce jointe.

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by ocemag** [comment]
Sujet :
Demande de prix acceptée

Contenu :

Bonjour,

Suite à l’analyse de votre demande, veuillez trouver ci-joint notre proposition de devis. Elle vaudra bon de commande si vous la signez en suivant ce lien : ONLINE_PAYMENT_URL
Pour visualiser votre devis cliquez sur la pièce jointe.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
