### ISSUE TITLE
RQ_Cloture-demande-prix

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#37]
Sujet :
Clôturation de la demande de prix. (refus)

Contenu :

Bonjour,

Nous accusons réception de votre demande de prix du __DATE_YMD__ . 
Nous vous remercions sincèrement de vos services, toutefois, après avoir minutieusement examiné votre offre, nous sommes malheureusement dans l’obligation de la décliner. En effet, le montant des frais inhérents au projet que nous souhaitons mettre en œuvre mentionné dans votre devis dépasse largement le budget dont nous disposons.
Nous tenons à vous réitérer nos remerciements et à vous assurer que nous ferons appel à vos services si nous souhaitons ajuster notre projet et le réaliser ou si nous avons à l’avenir d’autres projets.

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by ocemag** [comment]
Sujet :
Clôturation de la demande de prix.

Contenu :

Bonjour,

Nous accusons réception de votre demande de prix du DATE_YMD .
Nous vous remercions sincèrement de vos services, toutefois, après avoir minutieusement examiné votre offre, nous sommes malheureusement dans l’obligation de la décliner. En effet, le montant des frais inhérents au projet mentionné dans votre devis dépasse largement le budget dont nous disposons.
Nous tenons à vous réitérer nos remerciements et n'hésiterons pas à vous contacter à nouveau dans l'espoir d'une future collaboration.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
