### ISSUE TITLE
SI_Relance-facture-fournisseur

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#41]
Sujet :
Relance facture fournisseur :  __PROJECT_NAME__  __REF_CLIENT__

Contenu :

Bonjour,

Sauf erreur de notre part, notre facture N°__AMOUNT__ en date du __DATE_YMD__ d'un montant de __AMOUNT__ euros, n'a toujours pas été réglée à ce jour.
Nous pensons qu'il s'agit d'un oubli, et nous vous remercions de bien vouloir nous adresser dans les plus brefs délais votre règlement.

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by ocemag** [comment]
Sujet :
Relance facture fournisseur : PROJECT_NAME REF_CLIENT

Contenu :

Bonjour,

Sauf erreur de notre part, notre facture N°__AMOUNT__ en date du DATE_YMD d'un montant de AMOUNT euros, n'a toujours pas été réglée à ce jour.
Nous pensons qu'il s'agit d'un oubli, vous pouvez la régler en suivant ce lien : ONLINE_PAYMENT_URL

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
