### ISSUE TITLE
FA_Relance-facture

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#43]
Sujet:
Relance facture : __PROJECT_NAME__  __REF_CLIENT__

Contenu :

Bonjour,

Sauf erreur de notre part, nous n’avons à ce jour pas reçu le paiement de la facture n° __AMOUNT__ en date du __DATE_YMD__ pour un montant de __AMOUNT__ euros, alors même que cette facture arrivait à échéance le __DATE_YMD__.
Nous vous demandons de bien vouloir procéder à son règlement le plus rapidement possible. Vous trouverez en pièce jointe de ce courrier une copie de la facture. Veuillez ne pas tenir compte de cette lettre si votre règlement nous a été adressé avant la réception de courrier.

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by lmag** [comment]
PS : Si vous nous avez fourni un bon de commande ou une référence client vous la trouverez ici : REF_CLIENT

**Comment by ocemag** [comment]
Sujet:
Relance facture : PROJECT_NAME REF_CLIENT

Contenu :

Bonjour,

Sauf erreur de notre part, nous n’avons à ce jour pas reçu le paiement de la facture n° AMOUNT en date du DATE_YMD pour un montant de AMOUNT euros, alors même que cette facture arrivait à échéance le DATE_YMD.
Si vous nous avez fourni un bon de commande ou une référence client vous la trouverez ici : REF_CLIENT
Nous vous demandons de bien vouloir procéder à son règlement le plus rapidement possible. Vous trouverez en pièce jointe de ce courrier une copie de la facture. Veuillez ne pas tenir compte de cette lettre si votre règlement nous a été adressé avant la réception de courrier.

Il est possible de régler ce montant par [chèque, virement ou espèces.] ou de payer en ligne ici : ONLINE_PAYMENT_URL

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
