### ISSUE TITLE
FA_Relance-facture-2

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#44]
Sujet:
2ème relance facture :  __PROJECT_NAME__  __REF_CLIENT_

Contenu :

Bonjour,

Sauf erreur de notre part, notre facture N° __REF__ en date du __DATE_YMD__ d'un montant de __AMOUNT__ euros, n'a toujours pas été réglée à ce jour.
Nous pensons qu'il s'agit d'un oubli, et nous vous remercions de bien vouloir nous adresser dans les plus brefs délais votre règlement. Veuillez ne pas tenir compte de cette lettre si votre reglèment nous a été adressé avant la réception de ce courrier. 

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by ocemag** [comment]
Sujet:
2ème relance facture : PROJECT_NAME _REF_CLIENT

Contenu :

Bonjour,

Sauf erreur de notre part, notre facture n° REF en date du DATE_YMD d'un montant de AMOUNT euros, n'a toujours pas été réglée à ce jour.
Nous pensons qu'il s'agit d'un oubli, et nous vous remercions de bien vouloir nous adresser dans les plus brefs délais votre règlement. Veuillez ne pas tenir compte de cette lettre si votre reglèment nous a été adressé avant la réception de ce courrier.

Il est possible de régler ce montant par [chèque, virement ou espèces.] ou de payer en ligne ici : ONLINE_PAYMENT_URL

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
