### ISSUE TITLE
FA_Relance-avant-contentieux

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#45]
Sujet:
Relance facture avant contentieux :  __PROJECT_NAME__  __REF_CLIENT__

Contenu :

Bonjour,

Nous constatons que malgré plusieurs relances de notre part, la facture N° __REF__ d’un montant de __AMOUNT__ euros, demeure toujours impayée à ce jour.
Pour mettre fin à ce contentieux, nous vous recommandons vivement de régler votre dû dans un délai de __AMOUNT__ jours. A défaut nous nous verrons dans l’obligation de poursuivre ce recouvrement par voie judiciaire.
Vous pouvez voir votre facture en pièce jointe.

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by ocemag** [comment]
Sujet:
Relance facture avant contentieux : PROJECT_NAME REF_CLIENT

Contenu :

Bonjour,

Nous constatons que malgré plusieurs relances de notre part, la facture n° REF d’un montant de AMOUNT euros, demeure toujours impayée à ce jour.
Pour mettre fin à ce contentieux, nous vous recommandons vivement de régler votre dû dans un délai de AMOUNT jours. A défaut nous nous verrons dans l’obligation de poursuivre ce recouvrement par voie judiciaire.
Vous pouvez voir votre facture en pièce jointe. Il est possible de régler ce montant par [chèque, virement ou espèces.] ou de payer en ligne ici : ONLINE_PAYMENT_URL

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
