### ISSUE TITLE
FA_Relance-information-contentieux

### ISSUE THREAD

**Issue by elisa34** [Eoxia/dolitemplate#46]
Sujet:
Relance information contentieux :  __PROJECT_NAME__  __REF_CLIENT__

Contenu :

Bonjour,

Nous constatons que malgré plusieurs relances de notre part, la facture N° __REF__ d’un montant de __AMOUNT__ demeure toujours impayée à ce jour.
 Nous sommes donc au regret de vous informer du lancement de la procédure judiciaire. 

Bien cordialement,

Service administratif
__MYCOMPANY_NAME__
__MYCOMPANY_FULLADDRESS__
__MYCOMPANY_EMAIL__

**Comment by lmag** [comment]
Attention a partir de la version 14 relance automatique payante :
Conserve le nombre de relances ?
"Ceci est notre Dernier mail de relances concernant la facture N° REF d’un montant de AMOUNT avant la mise en procédure judiciaire."
@elisa34 numeroter les mails de relance et noter le process

**Comment by ocemag** [comment]
Sujet:
Relance information contentieux : PROJECT_NAME REF_CLIENT

Contenu :

Bonjour,

Nous constatons que malgré plusieurs relances de notre part, la facture N° REF d’un montant de AMOUNT demeure toujours impayée à ce jour.
Nous sommes donc au regret de vous informer du lancement de la procédure judiciaire.


Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
