### ISSUE TITLE
PR_Envoi-proposition

### ISSUE THREAD

**Issue by lmag** [Eoxia/dolitemplate#9]
Contenu du mail

**Comment by elisa34** [comment]
Sujet: 
Proposition commerciale

Bonjour, 

Je vous prie de trouver en pièce jointe notre proposition commerciale concernant __PROJECT_NAME__. La présente offre annule et remplace toute proposition antérieure. 
Nous attirons votre attention sur le fait que cette proposition commerciale est valable jusqu'au __DATE_END_PROPAL__.
Je vous remercie de bien vouloir nous retourner cette offre de prestation en y apposant la mention « bon pour accord », votre signature et la date.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL

**Comment by elisa34** [comment]
Modification clé date de fin vers date de fin de validité

**Comment by ocemag** [comment]
Sujet:
Proposition commerciale

Bonjour,

Je vous prie de trouver en pièce jointe notre proposition commerciale concernant le PROJECT_NAME.
Nous attirons votre attention sur le fait que cette proposition commerciale est valable jusqu'au DATE_END_PROPAL.
Je vous remercie de bien vouloir nous retourner cette offre de prestation signée éléctroniquement grâce à ce lien ONLINE_PAYMENT_URL.

Bien cordialement,

Service administratif
MYCOMPANY_NAME
MYCOMPANY_FULLADDRESS
MYCOMPANY_EMAIL
